# Generated by Django 5.2.7 on 2026-01-23 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_make_debt_item_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='tracker.sale'),
        ),
    ]
