# Generated by Django 5.1.6 on 2026-02-01 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_productcategory_supplier_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stationery_item',
            field=models.OneToOneField(blank=True, help_text='Link to corresponding stationery item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='tracker.stationeryitem'),
        ),
    ]
