# Generated by Django 5.1.6 on 2026-02-02 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product_type',
            field=models.CharField(choices=[('retail', 'Retail Sale Product'), ('wholesale', 'Whole Sale Product')], default='retail', max_length=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='retail_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retail_sale_items', to='tracker.stationeryitem'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='wholesale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_sale_items', to='tracker.product'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product_type', 'retail')), fields=('sale', 'retail_item'), name='unique_retail_sale_item'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product_type', 'wholesale')), fields=('sale', 'wholesale_item'), name='unique_wholesale_sale_item'),
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='item',
        ),
    ]
